### ISSUE TITLE
CaretShape.EmptyInside paint bug / caret of inactive window bug

### ISSUE THREAD

**Issue by veksha** [Alexey-T/ATSynEdit#319] opened 2023-05-31 02:21 UTC
after my recent patch: ...

```diff
-      if not FCaretShown then
+      if not FCaretShown and (Caret.OldRect <> R) then
```

... i noticed that caret shape EmptyInside has some flicker of non-empty caret shape.
i think it's because caret is not double-buffered.

so i made this change:

```diff
diff --git a/atsynedit/atsynedit.pas b/atsynedit/atsynedit.pas
index 5a6c010d..968480c3 100644
--- a/atsynedit/atsynedit.pas
+++ b/atsynedit/atsynedit.pas
@@ -7422,7 +7422,10 @@ begin
   if not DoubleBuffered then
     FCaretAllowNextBlink:= not FCaretAllowNextBlink;
 
-  DoPaintCarets(Canvas, true);
+  if not DoubleBuffered then
+    DoPaintCarets(Canvas, true)
+  else
+    DoPaintCarets(FBitmap.Canvas, true);
 end;
 
 procedure TATSynEdit.TimerScrollTick(Sender: TObject);
@@ -7666,7 +7669,10 @@ begin
       //CudaText issue #4250
       InflateRect(R, 1, 1);
       {$endif}
-      InvalidateRect(Handle, @R, false);
+      if not DoubleBuffered then
+        InvalidateRect(Handle, @R, false)
+      else
+        Canvas.CopyRect(R, FBitmap.Canvas, R);
     end;
   end;
 end;

```

this patch fixed two bugs: flickering of emptyinside caret and blinking of inactive window caret (don't know why, but it's nice)
(see videos below)

PS:
my first patch (with `(Caret.OldRect <> R)`) have made next block of code always unreachable. so i think it is safe to remove whole block altogether. i mean block to solve 'ghost caret on typing'. maybe with double-buffering there will be no ghosting. ( but i myself never noticed ghosting at all, with or without `(Caret.OldRect <> R)`).

**Comment by veksha** [comment] 2023-05-31 02:22
before:

https://github.com/Alexey-T/ATSynEdit/assets/275333/bf6736a6-6a4b-4067-85d5-b645c27c8a2f

after:

https://github.com/Alexey-T/ATSynEdit/assets/275333/1cc9f98b-6405-4981-983c-41ef99085cf6

**Comment by Alexey-T** [comment] 2023-05-31 07:57
On Mac and Qt5, it is prohibited to paint on canvas out of Paint event. path may do this (2nd part of it). please test on qt5.

**Comment by Alexey-T** [comment] 2023-05-31 08:11
with patch, Qt5 caret becomes NON-blinking.

**Comment by veksha** [comment] 2023-05-31 15:14
caret is blinking on main form while modal form is shown: is it a bug?
if so, then we can keep my patch but for **windows only** for now. since it fixes 2 bugs.
on other platform at least one bug still remains.

**Comment by Alexey-T** [comment] 2023-05-31 15:21
it is not a bug, it's misfeature.
TATSynEdit has OptCaretStopUnfocused prop, and it's even True (it's not changeble for user). but it works only with 2+ groups, not with additional modal forms.

this prop is read here in atsynedit.pas
```

procedure TATSynEdit.TimerBlinkTick(Sender: TObject);
begin
  if not FCaretShowEnabled then exit;
  if not Application.Active then exit;

  if FCaretStopUnfocused and not _IsFocused then
    if FCaretShown then
      exit; 
```
maybe _IsFocused has wrong result with modal forms?

**Comment by Alexey-T** [comment] 2023-05-31 16:28
_IsFocused works good. next line
`    if FCaretShown then`

is bad for modal form! if I comment it, blinking stops with modal form (e.g. OptEditor). but I dont like this fix - caret can freeze in state ON or in state OFF .

**Comment by veksha** [comment] 2023-05-31 17:07
can we somehow group this two `CanvasInvertRect` calls?

(in DoPaintCaretShape proc)
```pascal
...  
  CanvasInvertRect(C, ARect, Colors.Caret);

  if ACaretShape.EmptyInside then
  begin
    Inc(ARect.Left);
    Inc(ARect.Top);
    Dec(ARect.Right);
    Dec(ARect.Bottom);
    CanvasInvertRect(C, ARect, Colors.Caret);
  end
  else
...
```

i mean draw them on temp canvas, then copy to C canvas. so on windows will be no flickering.

**Comment by veksha** [comment] 2023-05-31 17:21
BTW:
```
    Inc(ARect.Left);
    Inc(ARect.Top);
    Dec(ARect.Right);
    Dec(ARect.Bottom);
```

can be replaced by `InflateRect(ARect, -1, -1);`

**Comment by veksha** [comment] 2023-05-31 17:48
yes. it fixes flickering on Windows without even using double-buffering for caret painting.
nice. we can close this issue after you apply this.

**Comment by Alexey-T** [comment] 2023-05-31 17:51
will reboot to linux and confirm its OK on Mac.

**Comment by Alexey-T** [comment] 2023-05-31 18:32
merged.

**Closed by Alexey-T** 2023-05-31 18:32 UTC
